language: python
python:
  - 2.7
  - 3.4
  - 3.5

#upgrade pip and install the dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

#running tests  
script:
  - pytest test_integers.py
  - pytest test_nparrays.py
  - pytest -q test_string.py --file input.txt


